### PR TITLE
Added fr Locale + Target + some more cars to the list

### PR DESCRIPTION
**Pull request by TonybynMp4**

### CODE REVIEW

**Comment by TonybynMp4** [comment]
Can't really do anything about that lint error, if i localize it, it spawns peds indefinitely
maybe i'm just dumb idk

**Comment by GhzGarage** [comment]
You shouldn't be adding target into a while loop

**Comment by TonybynMp4** [comment]
> You shouldn't be adding target into a while loop

Where should i add it then 🤔 i don't really see the problem there

**Comment by GhzGarage** [comment]
Including in a loop will call this export over and over because of this 
image

**Comment by TonybynMp4** [comment]
> Including in a loop will call this export over and over because of this 

Ok now i see what you meant, is it better with what i did in the last changes ? made it check to see if we already added it so that should prevent it from being called non stop

**Pull request closed without merging**
